version: '3.8'

volumes:
  es01_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es01
      o: bind

  es02_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es02
      o: bind

  es03_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es03
      o: bind

networks:
  elk-net:
    driver: bridge

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      
    ports:
      - 9200:9200
    networks:
      - elk-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Admin123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    ports:
      - 9201:9200

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Admin123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    ports:
      - 9202:9200
