version: '3.8'

volumes:

  es01_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es01
      o: bind

  es02_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es02
      o: bind

  es03_data:
    driver: local
    driver_opts:
      type: none
      device: /data/es03
      o: bind

  es01_log:
    driver: local
    driver_opts:
      type: none
      device: /data/log_es01
      o: bind

  es02_log:
    driver: local
    driver_opts:
      type: none
      device: /data/log_es02
      o: bind

  es03_log:
    driver: local
    driver_opts:
      type: none
      device: /data/log_es03
      o: bind

networks:
  elk-net:
    driver: bridge

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
      # - xpack.license.self_generated.type: "trial"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01_data:/usr/share/elasticsearch/data
      - es01_log:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - elk-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
      # - xpack.license.self_generated.type: "trial"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02_data:/usr/share/elasticsearch/data
      - es02_log:/usr/share/elasticsearch/logs
    networks:
      - elk-net
    ports:
      - 9201:9200

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
      # - xpack.license.self_generated.type: "trial"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es03_data:/usr/share/elasticsearch/data
      - es03_log:/usr/share/elasticsearch/logs
    networks:
      - elk-net
    ports:
      - 9202:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk-net
    depends_on:
      - es01
      - es02
      - es03