version: '3.8'
services:
  metric1:
    image: docker.elastic.co/beats/metricbeat:7.10.0
    # user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - esnetwork
    deploy:
      placement:
        constraints: [ node.hostname == docker1.domain.local ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 2G
  
networks:
  esnetwork:
    external: true

volumes:
  vol1:
    driver: local