version: '3.8'

services:
  create_certs:
    image: centos:centos8.3.2011
    container_name: set_passwd
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - SETPASS_RESET=${SETPASS_RESET}
      - SETPASS_elastic=${SETPASS_elastic}
      - SETPASS_apm_system=${SETPASS_apm_system}
      - SETPASS_kibana_system=${SETPASS_kibana_system}
      - SETPASS_logstash_system=${SETPASS_logstash_system}
      - SETPASS_beats_system=${SETPASS_beats_system}
      - SETPASS_remote_monitoring_user=${SETPASS_remote_monitoring_user}
    # command: >
    #   bash -c '
    #     # echo "installing unzip..."
    #     # yum install -y -e 0 unzip;
    #     if [[ ! -f /certs/bundle.zip ]]; then
    #       bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
    #       unzip /certs/bundle.zip -d /certs;
    #     else
    #       echo "/certs/bundle.zip already exist!"
    #     fi;
    #     chown -R 1000:0 /certs
    #   '
    working_dir: /
    command: >
      bash -c '
        env;
        echo "SETPASS_RESET = $SETPASS_RESET";
        if [[ "$SETPASS_RESET" == "true" || "$SETPASS_RESET" == "True" || "$SETPASS_RESET" == "TRUE" || "$SETPASS_RESET" == "1" ]]; then
          echo "SETPASS_RESET = True";
          echo "All password for reserved elasticsearch user will be reset by this service";
          yum install -y python38;
          pip3 install requests;
          env;
          python3 app.py;
        else
          echo "SETPASS_RESET = False";
          echo "NO Password will be reset by this service";
        fi
      '

    volumes:
      - certs:/certs
      - ./es-setup/app.py:/app.py
    networks:
      - elastic

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /data/certs
      o: bind

networks:
  elastic:
    driver: bridge