version: '3.8'

services:
  create_certs:
    # image: centos:centos8.3.2011
    image: python:3.9.1-slim-buster
    container_name: set_passwd
    # command: >
    #   bash -c '
    #     # echo "installing unzip..."
    #     # yum install -y -e 0 unzip;
    #     if [[ ! -f /certs/bundle.zip ]]; then
    #       bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
    #       unzip /certs/bundle.zip -d /certs;
    #     else
    #       echo "/certs/bundle.zip already exist!"
    #     fi;
    #     chown -R 1000:0 /certs
    #   '
    # working_dir: /usr/share/elasticsearch
    # command: >
    #   bash -c '
    #     yum install -y python38;
    #     /bin/bash
    #   '

    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
    networks:
      - elastic

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /data/certs
      o: bind

networks:
  elastic:
    driver: bridge