version: '3.8'

services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - network.publish_host=192.168.1.247
      - cluster.name=es-cluster
      - discovery.seed_hosts=192.168.1.246,192.168.1.248
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  ls02:
    image: docker.elastic.co/logstash/logstash:${VERSION}
    container_name: ls02
    volumes:
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ../logstash/pipeline:/usr/share/logstash/pipeline:ro
      - log_data:/data/log/
      - certs:/certs
    environment:
      - node.name=ls02
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - ELASTIC_HOST="https://192.168.1.246:9200,https://192.168.1.247:9200,https://192.168.1.248:9200"
      - "LS_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9600 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data02:
    driver: local
  log_data:
    driver: local
    driver_opts:
      type: none
      device: /data/log
      o: bind
  certs:
    driver: local
    driver_opts:
      type: none
      device: /data/certs
      o: bind

networks: 
  elastic:
    driver: bridge